---
title: "Problem Set - Two Variables"
author: "Sumit Kant"
date: "31 March 2017"
output: html_document
---



```{r}
setwd("D:/IIML/Crisp Analytics/Udacity/DAta analysis with R/Problem Set - Two Variables/")
library(ggplot2) #must load the ggplot package first 
data(diamonds) #loads the diamonds data set since it comes with the ggplot package
```
# Your first task is to create a
# scatterplot of price vs x.
# using the ggplot syntax.

```{r}
ggplot(data = diamonds, aes(x = x, y = price)) + geom_point()
```
## Correlations

```{r}
cor.test(diamonds$price, diamonds$x)
cor.test(diamonds$price, diamonds$y)
cor.test(diamonds$price, diamonds$z)
```

# Scatterplot - Price vs DEpth
```{r}
ggplot(data = diamonds, aes(x = depth, y = price)) + geom_point(alpha = 0.01) +
  scale_x_continuous(breaks = seq(43,79,2))

```
# Most number of diamonds
```{r}
quantile(diamonds$depth, probs = 0.95)
quantile(diamonds$depth, probs = 0.05)
# hence 90% of the diamonds lie between 59 and 64
```
# Correlation - Depth vs Price
```{r}
cor.test(diamonds$depth, diamonds$price)
```
# Scatterplot - Price vs carat
```{r}
ggplot(diamonds, aes(carat, price)) + geom_point()

ggplot(diamonds[diamonds$carat < quantile(diamonds$carat, 0.99),], aes(carat, price) ) + geom_point()
```

# Create a scatterplot of price vs. volume (x * y * z).

```{r}
diamonds$volume <- diamonds$x * diamonds$y * diamonds$z
# scatterplot

ggplot(diamonds, aes(volume, price)) + geom_point()
library(dplyr)
diamonds_sub_vol <- diamonds[diamonds$volume < quantile(diamonds$volume, 0.99),]
diamonds_sub_vol <- diamonds_sub_vol[!diamonds_sub_vol$volume == 0,]
diamonds_sub_vol <- diamonds_sub_vol[!diamonds_sub_vol$volume >= 800,]

ggplot(diamonds_sub_vol, aes(volume, price)) + 
  geom_point(alpha = 0.1) + 
  geom_smooth(method = "lm")

cor.test(diamonds_sub_vol$volume, diamonds_sub_vol$price)


```

# DIamonds by Clarity
```{r}
library(dplyr)
?group_by
clarity_groups <- group_by(diamonds, clarity)

diamondsByClarity <- summarise(clarity_groups, 
                          mean_price = mean(price),
                          median_price = median(price),
                          min_price = min(price),
                          max_price = max(price),
                          n = n())
```

# Two bar plots
```{r}
data(diamonds)
library(dplyr)

diamonds_by_clarity <- group_by(diamonds, clarity)
diamonds_mp_by_clarity <- summarise(diamonds_by_clarity, mean_price = mean(price))

p1 <- ggplot( data = diamonds_mp_by_clarity, aes(x = clarity, y= mean_price, fill = clarity )) + geom_bar(stat = "identity")

diamonds_by_color <- group_by(diamonds, color)
diamonds_mp_by_color <- summarise(diamonds_by_color, mean_price = mean(price))

p2 <- ggplot(diamonds_mp_by_color, aes(x = color, y = mean_price, fill = color)) + geom_bar(stat = 'identity')

library(gridExtra)
grid.arrange(p1,p2, nrow=1)
# ggsave('mean_price_bar_pplots_color.png', width = 8, height = 4.5, dpi = 400)

```




